### ISSUE TITLE
Procedure to add submitted projects on the website

### ISSUE THREAD

**Issue by Remi-Gau** [ohbm/hackathon2020#90]
Since we are starting to get some projects I was wondering when we should start putting them on the website. 

Should I wait for a green light from the project advisor team?

@cmaumet @anibalsolon @complexbrains

**Comment by Remi-Gau** [comment]
Also this is the content of what will be shown about each project on the website.

Let me know if you think something else should be added.

```yml
title: "Your awesome project"
image: whatever.png
details: "Tell us about what you want to achieve. More information here:
<a href=https://github.com/ohbm/hackathon2020/issues/INSERT_ISSUE_NUMBER_HERE</a>"
```
